server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

      default-filters:
        - name: StripPrefix
          args:
            parts: 1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG