jwt:
  secret: qaq9P3N0AmmJBrWg2x0whCdGGg9UoZZnU86d6bFdxj+r6rnANOcXFcnIVOueTnlP
  devToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkRldi1Vc2VyIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.HqlzbTcDm_ADxxBlHGoCb-67sdMBOw4xjListL8CBrU

logging:
  level:
    org.springframework.cloud.gateway: DEBUG