version: "3.8"
services:
  api-gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: api-gateway:latest
    ports:
      - "8080:8080"
    networks:
      api_gateway_network:
        ipv4_address: 172.17.0.2
    environment:
      SPRING_PROFILES_ACTIVE: dev
networks:
  api_gateway_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.2/16

