version: "3.8"
services:
  api-gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/gatewaydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: dev

