name: Listen for Deploy PRE

on:
  issue_comment:
    types:
      - created

jobs:
  handle-slash-command:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the command is `/deploy-pre`
        id: check_command
        uses: peter-evans/slash-command-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: /deploy-pre

      - name: Trigger Deploy Workflow
        if: steps.check_command.outputs.command == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "deploy-pre.yml", # Name of the deploy workflow file
              ref: "develop"
            })