name: On PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  call-java-code-quality-workflow:
    uses: zerodaycode/app-summoner-sync/.github/workflows/trigger-java-code-quality.yml@feature/new-github-actions
