name: Main and Develop PR Handlers

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  call-java-code-quality-workflow:
    uses: zerodaycode/app-summoners-sync/.github/workflows/unified-code-quality.yml@feature/new-github-actions
  call-changelog-workflow:
    uses: zerodaycode/app-summoners-sync/.github/workflows/pr-changelog-preview.yml@feature/new-github-actions