name: Release workflow

on:
  push:
    branches:
      - main

jobs:
  call-release-workflow:
    uses: ${{ github.repository_owner }}/app-summoners-sync/.github/workflows/release-workflow.yml@feature/new-github-actions
